# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsummation.proto\"-\n\x05Input\x12\x11\n\tnumberOne\x18\x01 \x01(\x05\x12\x11\n\tnumberTwo\x18\x02 \x01(\x05\"\x15\n\x06Output\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32%\n\tSummation\x12\x18\n\x03\x61\x64\x64\x12\x06.Input\x1a\x07.Output\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUT._serialized_start=19
  _INPUT._serialized_end=64
  _OUTPUT._serialized_start=66
  _OUTPUT._serialized_end=87
  _SUMMATION._serialized_start=89
  _SUMMATION._serialized_end=126
# @@protoc_insertion_point(module_scope)
